### ISSUE TITLE
你好，请问如何修改生成的html网页模板？

### ISSUE THREAD

**Issue by whistle003** [DDS-Derek/LinuxDir2HTML-Docker#7]
大佬好，这个项目很实用，请问如何修改生成的html网页模板？

**Comment by DDSDerek** [comment]
这需要去修改原项目的 https://github.com/homeisfar/LinuxDir2HTML/blob/master/linuxdir2html/template.html 这个文件。

然后自己通过我提供的镜像源码编译镜像。
需要更改的部分就是这行，更改为自己fork后的仓库地址。 https://github.com/DDS-Derek/LinuxDir2HTML-Docker/blob/c6e7ec5161ecd37cc26038f8e5b629294ca9fc43/Dockerfile#L23

**Comment by whistle003** [comment]
> 这需要去修改原项目的 https://github.com/homeisfar/LinuxDir2HTML/blob/master/linuxdir2html/template.html 这个文件。
> 
> 然后自己通过我提供的镜像源码编译镜像。 需要更改的部分就是这行，更改为自己fork后的仓库地址。
> 
> https://github.com/DDS-Derek/LinuxDir2HTML-Docker/blob/c6e7ec5161ecd37cc26038f8e5b629294ca9fc43/Dockerfile#L23

多谢大佬。还有一个小问题：如何在设置cron定时的情况下立即运行扫描呢？

**Comment by DDSDerek** [comment]
重启容器会立刻执行一次
